#!/usr/bin/env bash

set -e

rm -rf 'build/'

mkdir -p 'build/js/'
mkdir -p 'build/css/'

browserify -d 'src/ts/index.tsx' -p [tsify] -t envify | uglifyjs --compress --mangle --source-map content='inline',filename='build/js/index.js.map',url='index.js.map' --output 'build/js/index.js'
lessc 'src/less/index.less' 'build/css/index.css' --silent --compress && postcss --use autoprefixer -r 'build/css/index.css'
